server.port=${PORT:8080}
spring.application.name=donaciones-service
spring.threads.virtual.enabled=true

// TODO: Utilizar variables de entorno
donatrack.openapi.title=DonaTrack - Servicio de Donaciones
donatrack.openapi.version=v1
donatrack.openapi.description=API REST para gestionar personas donantes, donaciones, entidades beneficiarias, necesidades y asignaciones.
donatrack.openapi.server-url=http://localhost:8080
donatrack.openapi.server-description=Servicio de Donaciones local