server.port=${PORT:8080}
spring.application.name=donaciones-service
spring.threads.virtual.enabled=true

# RabbitMQ Config with Environment Variable Injections
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

// TODO: Utilizar variables de entorno
donatrack.openapi.title=DonaTrack - Servicio de Donaciones
donatrack.openapi.version=v1
donatrack.openapi.description=API REST para gestionar personas donantes, donaciones, entidades beneficiarias, necesidades y asignaciones.
donatrack.openapi.server-url=http://localhost:8080
donatrack.openapi.server-description=Servicio de Donaciones local