package grupo5.common.exceptions;

public enum ErrorCatalog {
  // === INFRAESTRUCTURA (0xx) ===
  CSV_READ_ERROR("ERR-INF-001"),
  CSV_PROCESS_ERROR("ERR-INF-002"),

  // === PERSONAS Y DIRECCIÓN (1xx) ===
  HUMANA_NOMBRE_VACIO("ERR-VAL-101"),
  HUMANA_APELLIDO_VACIO("ERR-VAL-102"),
  HUMANA_FECHA_NACIMIENTO_FUTURA("ERR-VAL-103"),
  JURIDICA_SIN_REPRESENTANTE_INICIAL("ERR-VAL-104"),
  JURIDICA_AGREGAR_REPRESENTANTE_NULO("ERR-VAL-105"),
  JURIDICA_QUITAR_REPRESENTANTE_INEXISTENTE("ERR-VAL-106"),
  JURIDICA_SIN_REPRESENTANTES_RESTANTES("ERR-EST-107"),
  DIRECCION_CALLE_VACIA("ERR-VAL-108"),
  DIRECCION_ALTURA_INVALIDA("ERR-VAL-109"),
  DIRECCION_CODIGO_POSTAL_VACIO("ERR-VAL-110"),
  DIRECCION_LOCALIDAD_NULA("ERR-VAL-111"),

  // === DONANTES Y DONACIONES (2xx) ===
  DONANTE_SIN_PERSONA("ERR-VAL-201"),
  DONACION_SIN_DONANTE("ERR-VAL-202"),
  DONACION_ITEM_NULO("ERR-VAL-203"),
  DONACION_ITEM_YA_AGREGADO("ERR-VAL-204"),
  DONACION_ITEM_NO_PERTENECE("ERR-VAL-205"),
  ITEM_DONACION_SIN_BIEN("ERR-VAL-206"),
  ITEM_DONACION_CANTIDAD_INVALIDA("ERR-VAL-207"),

  // === BIENES Y CATEGORÍAS (3xx) ===
  DESCRIPCION_BIEN_VACIA("ERR-VAL-301"),
  BIEN_SIN_SUBCATEGORIA("ERR-VAL-302"),
  BIEN_VENCIMIENTO_REQUERIDO("ERR-VAL-303"),
  BIEN_VENCIMIENTO_NO_PERMITIDO("ERR-VAL-304"),
  BIEN_ESTADO_REQUERIDO("ERR-VAL-305"),
  CATEGORIA_SIN_NOMBRE("ERR-VAL-306"),
  CATEGORIA_SIN_USO_DEFINIDO("ERR-VAL-307"),
  CATEGORIA_SIN_VENCIMIENTO_DEFINIDO("ERR-VAL-308"),
  CATEGORIA_SIN_UNIDAD("ERR-VAL-309"),
  SUBCATEGORIA_SIN_CATEGORIA("ERR-VAL-310"),
  SUBCATEGORIA_SIN_NOMBRE("ERR-VAL-311"),

  // === SEGMENTACIONES (4xx) ===
  DONACION_INDEPENDIENTE_ORIGINAL_NULA("ERR-VAL-403"),
  DONACION_INDEPENDIENTE_AGREGAR_ITEM_NULO("ERR-VAL-404"),
  DONACION_INDEPENDIENTE_QUITAR_ITEM_INEXISTENTE("ERR-VAL-405"),
  FRAGMENTACION_CANTIDAD_INSUFICIENTE("ERR-EST-406"),
  ITEM_DONACION_INDEPENDIENTE_SIN_BIEN("ERR-VAL-407"),
  ITEM_DONACION_INDEPENDIENTE_CANTIDAD_INVALIDA("ERR-VAL-408"),
  ITEM_DONACION_INDEPENDIENTE_FRAGMENTACION_INVALIDA("ERR-EST-409"),

  // === BENEFICIARIOS Y NECESIDADES (5xx) ===
  FECHA_ASIGNACION_FUTURA("ERR-VAL-501"),
  ENTIDAD_BENEFICIARIA_SIN_PERSONA_JURIDICA("ERR-VAL-502"),
  AGREGAR_NECESIDAD_NULA("ERR-VAL-503"),
  NECESIDAD_YA_REGISTRADA("ERR-VAL-504"),
  NECESIDAD_NO_PERTENECE_A_ENTIDAD("ERR-VAL-505"),
  NECESIDAD_SIN_SUBCATEGORIA("ERR-VAL-506"),
  CANTIDAD_NECESITADA_INVALIDA("ERR-VAL-507"),
  DESCRIPCION_NECESIDAD_VACIA("ERR-VAL-508"),
  ASIGNAR_DONACION_NULA("ERR-VAL-509"),
  DONACION_YA_ASIGNADA("ERR-VAL-510"),
  DONACION_NO_PERTENECE_A_NECESIDAD("ERR-VAL-511"),
  NECESIDAD_RECURRENTE_SIN_PERIODO("ERR-VAL-512"),
  FECHA_INICIO_NULA("ERR-VAL-513"),
  FECHA_INICIO_FUTURA("ERR-VAL-514"),
  SIN_PERIODO_ACTIVO("ERR-EST-515"),
  PERIODO_DONACION_NULA("ERR-VAL-516"),
  TEST_FECHA_INVALIDA("ERR-VAL-999");

  private final String code;

  ErrorCatalog(String code) {
    this.code = code;
  }

  public String getCode() {
    return this.code;
  }
}
