server.port=8082
spring.application.name=incentivos-service
spring.threads.virtual.enabled=true

# URL del servicio de donaciones (para consultar historial)
donaciones.service.url=http://localhost:8080

# URL del servicio de notificaciones
notificaciones.service.url=http://localhost:8081


