server.port=${PORT:8081}
spring.application.name=notificaciones-service
spring.threads.virtual.enabled=true
spring.task.scheduling.enabled=false

# RabbitMQ Config with Environment Variable Injections
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
