# ==========================================
# PERFIL POSTGRESQL (Producción / Preprod / Docker)
# ==========================================
# Reactivar autoconfiguración de base de datos relacional
spring.autoconfigure.exclude=

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/donatrack?currentSchema=notificaciones}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:notificaciones_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:notif_pass_2026}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=notificaciones
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway Migration
spring.flyway.enabled=true
spring.flyway.schemas=notificaciones
spring.flyway.locations=classpath:db/migration