services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: club
      POSTGRES_USER: club_user
      POSTGRES_PASSWORD: club_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Ejecuta tu script al crear la base de datos por primera vez:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata: