# ==========================================
# RUTAS: DONACIONES SERVICE
# ==========================================
donatrack.routes.donaciones.asignacion-base=/api/asignaciones/ejecuciones

donatrack.routes.donaciones.categorias-base=/api/categorias
donatrack.routes.donaciones.categorias-id=/{id}

donatrack.routes.donaciones.donaciones-base=/api/donaciones

donatrack.routes.donaciones.donaciones-independientes-base=/donaciones-independientes
donatrack.routes.donaciones.donaciones-independientes-id-estado=/{id}/estado

donatrack.routes.donaciones.donantes-base=/api/donantes
donatrack.routes.donaciones.donantes-id=/{id}
donatrack.routes.donaciones.donantes-archivos=/archivos

donatrack.routes.donaciones.entidades-base=/api/entidades
donatrack.routes.donaciones.entidades-id=/{id}

donatrack.routes.donaciones.items-normalizados-base=/api/items-normalizados
donatrack.routes.donaciones.items-normalizados-pendientes=/pendientes
donatrack.routes.donaciones.items-normalizados-id=/{id}

donatrack.routes.donaciones.necesidades-base=/api/necesidades

donatrack.routes.donaciones.personas-base=/api/personas
donatrack.routes.donaciones.personas-id=/{id}

donatrack.routes.donaciones.propuestas-base=/api/asignaciones/propuestas
donatrack.routes.donaciones.propuestas-id-estado=/{id}/estado

donatrack.routes.donaciones.subcategorias-base=/api/subcategorias
donatrack.routes.donaciones.subcategorias-id=/{id}

# ==========================================
# RUTAS: INCENTIVOS SERVICE
# ==========================================
donatrack.routes.incentivos.base=/api/incentivos
donatrack.routes.incentivos.donaciones=/donaciones
donatrack.routes.incentivos.donaciones-exitosa=/donaciones/exitosa
donatrack.routes.incentivos.donantes-id=/donantes/{donanteId}
donatrack.routes.incentivos.donantes-id-metricas=/donantes/{donanteId}/metricas
donatrack.routes.incentivos.donantes-id-misiones=/donantes/{donanteId}/misiones
donatrack.routes.incentivos.donantes-id-insignias=/donantes/{donanteId}/insignias
donatrack.routes.incentivos.donantes-id-visibilidad=/donantes/{donanteId}/insignias/{nombreInsignia}/visibilidad
donatrack.routes.incentivos.admin-resumen=/admin/resumen

donatrack.routes.incentivos.ranking-base=/api/incentivos/ranking
donatrack.routes.incentivos.ranking-ultimo=/ultimo
donatrack.routes.incentivos.ranking-historial=/historial
donatrack.routes.incentivos.ranking-calcular=/calcular

# ==========================================
# RUTAS: NOTIFICACIONES SERVICE
# ==========================================
donatrack.routes.notificaciones.personas-base=/api/notificaciones/personas
donatrack.routes.notificaciones.personas-id=/{id}

donatrack.routes.notificaciones.notificaciones-base=/notificaciones
donatrack.routes.notificaciones.notificaciones-persona-id=/persona/{personaId}
